[versions]
agp = "8.8.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"

# Google Play Services (GMS)
playServicesVision = "20.1.3"

# ML Kit
mlkitFaceDetection = "16.1.5"

# PyTorch Android
pytorchAndroid = "1.12.2"
pytorchAndroidTorchvision = "1.12.2"

# CameraX
cameraCore = "1.3.0"
cameraCamera2 = "1.3.0"
cameraLifecycle = "1.3.0"
cameraView = "1.3.0"
cameraExtensions = "1.1.0"

# Concurrent
guava = "32.1.2-android"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Google Play Services 依赖
play-services-vision = { group = "com.google.android.gms", name = "play-services-vision", version.ref = "playServicesVision" }

# ML Kit 依赖
mlkit-face-detection = { group = "com.google.mlkit", name = "face-detection", version.ref = "mlkitFaceDetection" }

# PyTorch Android 依赖
pytorch-android = { group = "org.pytorch", name = "pytorch_android", version.ref = "pytorchAndroid" }
pytorch-android-torchvision = { group = "org.pytorch", name = "pytorch_android_torchvision", version.ref = "pytorchAndroidTorchvision" }

# CameraX 依赖
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraCamera2" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraLifecycle" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraView" }
camera-extensions= { group = "androidx.camera", name = "camera-extensions", version.ref = "cameraExtensions" }

# Guava (CameraX需要)
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

